name: Go Test Build and Deploy

on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/upload-artifact@v3
      with:
          name: lebena-artifact
          path: ./lebena-binary

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: lebena-artifact
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT }}
           source: ./lebena-binary
           target: "/home/${{ secrets.USERNAME }}/lebena"

 
